### ISSUE TITLE
Adapt width of <td> to content

### ISSUE THREAD

**Issue by alebarbaja** [CodyHouse/cd-table-v2-changelog#1]
Hi! The <td> elements on the table, when there is available space, take all the space leaving too mucho spacing between the others `<td>`.

There is a way to adapt the width of the `<td>` to their content? And that all columns have the same width that the width of the `<td>` most large.?

<img width="1618" alt="Screenshot 2020-07-30 at 13 21 16" src="https://user-images.githubusercontent.com/28918805/88917194-a9c5d300-d267-11ea-8756-2d673229fc01.png">

**Comment by claudia-romano** [comment]
Hi, 
you can set a fixed width  for your table columns. 
E.g., you could add a width: 16.7% to your columns so that they all have the same width, or you can set different percentage width for the different columns (make sure the sum is 100%).

Cheers!
