### ISSUE TITLE
missing opening span tags in salary row value

### ISSUE THREAD

**Issue by ivarlovlie** [CodyHouse/cd-table-v2-changelog#2]
last line of all rows is: 
`<td class="tbl__cell text-right" role="cell">$180,000</span></td>`
which im guessing should be:
`<td class="tbl__cell text-right" role="cell">$180,000</td>`

**Comment by claudia-romano** [comment]
Thanks for the heads-up! We have updated the component fixing the typo:
https://codyhouse.co/ds/components/app/table-v2

Cheers!
